language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
# - 3.8-dev
# - 3.7
- 3.6

# env: CMAKE_VER=3.14.5

matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script:
    - flake8
    - mypy .
#  - os: osx
#    language: minimal
#    install: pip3 install -e .[tests]
#  - os: windows
#    language: minimal
#    before_install:
#    - choco install python3
#    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

install:
- pip install -e .[tests,cov]
- pip install meson
# - pip install cmakeutils
# - cmake_setup $CMAKE_VER
# - export PATH="$HOME/.local/cmake-$CMAKE_VER-Linux-x86_64/bin:$PATH"

script:
- pytest -v

- buildmc -s tests -buildsys meson -test
- buildmc -s tests -buildsys cmake -test
